agents:
  queue: kubernetes
steps:
- name: upload artifact
  artifact_paths: test.txt
  plugins:
  - kubernetes:
      podSpec:
        containers:
        - image: alpine:latest
          command: [ash, -c, echo "hello world" > test.txt && sleep 10 && false]
