agents:
  queue: kubernetes
steps:
- name: ":go::lint-roller: Lint"
  plugins:
  - kubernetes:
      podSpec:
        containers:
        - image: golangci/golangci-lint:v1.52.0
          command: [golangci-lint, run, -v, --timeout 10m]
- name: ":go::test_tube: Test"
  artifact_paths: junit-*.xml
  plugins:
  - kubernetes:
      sidecars:
        - image: postgres:15-alpine
          envFrom:
            - secretRef:
                name: postgres-test-secrets
      podSpec:
        serviceAccount: postgres-test
        containers:
        - image: golang:1.20.2-alpine
          envFrom:
            - secretRef:
                name: postgres-test-secrets
          env:
          - name: CGO_ENABLED
            value: "0"
          command: [.buildkite/steps/test.sh]
- name: ":go::hammer: Build"
  plugins:
  - kubernetes:
      podSpec:
        nodeSelector:
          kubernetes.io/arch: arm64
        serviceAccount: ecr-push
        containers:
        - name: docker
          image: buildkite/agent:3.45.0
          command: [.buildkite/steps/build.sh]
          volumeMounts:
          - name: buildkit-client
            mountPath: /buildkit/certs
        volumes:
        - name: buildkit-client
          secret:
            secretName: buildkit-client-certs
