steps:
  - name: ":go::lint-roller: Lint"
    agents:
      queue: kubernetes
    env:
      BUILDKITE_SHELL: sh -ec
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: golangci/golangci-lint:v1.51.1
                command:
                  - golangci-lint
                args:
                  - run
                  - -v
                  - --timeout 10m
  - name: ":go::test_tube: Test"
    agents:
      queue: kubernetes
    env:
      BUILDKITE_SHELL: sh -ec
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: golang:1.20.1-alpine
                env:
                  - name: CGO_ENABLED
                    value: "0"
                command:
                  - go
                args:
                  - test
                  - ./...
  - name: ":go::hammer: Build"
    agents:
      queue: kubernetes
    env:
      BUILDKITE_SHELL: sh -ec
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - name: docker
                image: crazymax/docker:latest
                command: [.buildkite/steps/build.sh]
                volumeMounts:
                - name: buildkit-client
                  mountPath: /buildkit/certs
            volumes:
            - name: buildkit-client
              secret:
                secretName: buildkit-client-certs
