agents:
  queue: kubernetes
steps:
- label: ":git:"
  plugins:
  - kubernetes:
      podSpec:
        containers:
        - image: alpine:latest
          command: [ash]
          args:
          - -c
          - '"echo $NEW_KEY"'
          envFrom:
          - secretRef:
              name: postgres-test-secrets
