steps:
- name: ":go::lint-roller: Lint"
  agents:
    queue: kubernetes
  env:
    BUILDKITE_SHELL: sh -ec
  plugins:
  - kubernetes:
     podSpec:
      containers:
      - image: golangci/golangci-lint:v1.51.9
        command:
        - golangci-lint
        args:
        - run
        - -v
        - --timeout 10m
