agents:
  queue: kubernetes
steps:
- name: "upload artifact"
  artifact_paths: test.txt
  command: echo "hello world" > test.txt
  plugins:
  - kubernetes:
      podSpec:
        containers:
        - image: alpine:latest
